name: Docker Image CI

on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 10 * * *'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  check:
    runs-on: ubuntu-latest
#     outputs:
#       checked: ${{ steps.ischeck.outputs.checked }}
    steps:
      - uses: actions/checkout@v3
      
      # Runs a single command using the runners shell
      - name: Run check script
        id: ischeck
        run: |
          IS_UPDATE=$(sh check_update.sh | grep 'Need Update'|wc -l)
          echo $IS_UPDATE
          echo "checked=$IS_UPDATE" >> $GITHUB_OUTPUT
        
      - name: Add & Commit
        # You may pin to the exact commit or the version.
        # uses: EndBug/add-and-commit@050a66787244b10a4874a2a5f682130263edc192
        uses: EndBug/add-and-commit@v9.1.1
        with:
          # Arguments for the git add command
          add: current_release
          message: update_release
          commit: current_release 
          # The name of the custom committer you want to use

  build:

    needs: check
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    if: ${{ needs.check.outputs.checked == 1 }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Run Download script
        run: sh download_update.sh
        
        
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: realforcez/frp:latest
